name: Joseph Tesfaye
avatar: https://gravatar.loli.net/avatar/167bb330a4095f88f26e379608c94328?s=360
title: Software Engineer
links:
  - label: About
    icon: fa-user-circle
    url: https://josephtesfaye.com/josephs-blog/about
  - label: Github
    icon: brands fa-github
    url: https://github.com/josephtesfaye
  - label: Stack Overflow
    icon: brands fa-stack-overflow
    url: https://stackoverflow.com/users/4357087
  - label: Twitter
    icon: brands fa-twitter
    url: https://twitter.com/josephtesfaye_
